# Build settings
markdown:         kramdown
highlighter:      rouge
permalink:        pretty
paginate:         5 # jekyll-paginate plugin is enabled by default
gems:
  - jekyll-sitemap

# Social handles
social:
  twitter: jacobemcken
  disqus_short_name: jacobemcken

# Setup
title:            Jacob Emcken
tagline:          'There is no silver bullet'
description:      "Blogging about a software developer's findings"
url:              https://www.emcken.dk
baseurl:          /

# Google Analytics
google_analytics_tracking_id: UA-896990-1

author:
  name:           'Jacob Emcken'
  url:            https://twitter.com/mdo
