# Dependencies
markdown:         kramdown
highlighter:      rouge

# Social handles
social:
  twitter: jacobemcken
  googleplus: JacobEmcken

# Permalinks
permalink:        pretty

# Setup
title:            Jacob Emcken
tagline:          'There is no silver bullet'
description:      "Blogging about a software developer's findings"
url:              http://www.emcken.dk
baseurl:          /
disqus_short_name: jacobemcken

# Google Analytics
google_analytics_tracking_id: UA-896990-1

author:
  name:           'Jacob Emcken'
  url:            https://twitter.com/mdo

paginate:         5
