# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jacob Emcken
tagline:          'There is no silver bullet'
url:              http://emcken.dk
baseurl:          /
disqus_short_name: jacobemcken

# Google Analytics
google_analytics_tracking_id: UA-896990-1

author:
  name:           'Jacob Emcken'
  url:            https://twitter.com/mdo

paginate:         5
